### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by michaltowilk** [Globegitter/chartist-plugin-tooltip#1]
Hi, 
I have copied example "With descriptive text" from master page and it is not working at all. Any errors, any extra markup. Could you provide us with some demo??

**Comment by Globegitter** [comment]
That is odd. I am not here for a while but I have a demo page where I am using the plugin myself if it helps anything: https://uk-pubfund.herokuapp.com/dashboard

As soon as I am back in my machine can try to provide a better demo with Screenshot.

**Comment by Globegitter** [comment]
@michaltowilk Could you try again? I fixed a bug in the latest version `0.0.8`

**Comment by Globegitter** [comment]
Check out http://gionkunz.github.io/chartist-js/plugins.html#tooltip-plugin
