### ISSUE TITLE
chart is not appearing!

### ISSUE THREAD

**Issue by jehad1990** [Globegitter/chartist-plugin-tooltip#24]
I spent hours trying to figure out what is the wrong with this plugin!

once I add the plugin call, the whole chart will disappear. I used the following to call the js file:
`<script src="js/chartist-plugin-tooltip.min.js"></script>`

any idea?

**Comment by gionkunz** [comment]
Did you include the plugin after the chartist script? Maybe you can post the whole part of your HTML where you include Chartist.

**Comment by jehad1990** [comment]
Well it works now but without my chart options; if I added the options, the tooltip is not appearing.

Here is my code:
`<script>
var responsiveOptions = [
  ['screen and (max-width: 900px)', {
    seriesBarDistance: 15,
  }],
  ['screen and (max-width: 600px)', {
    seriesBarDistance: 10,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value[0];
      }
    }
  }],
  ['screen and (max-width: 550px)', {
    seriesBarDistance: 5,
	height:280,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value[0];
      }
    }
  }]
];
new Chartist.Bar('#bar', {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  series: [
	[52, 55, 46, 25, 98, 54, 24, 33, 48, 45, 24, 76],
    [52, 55, 46, 25, 98, 54, 24, 33, 48, 45, 24, 76]
    
  ]
},{
	seriesBarDistance: 20
}, responsiveOptions,{
  plugins: [
    Chartist.plugins.tooltip()
  ]
});
</script>`

**Comment by dominicrico** [comment]
The plugins are part of the options.

```javascript
var responsiveOptions = [
  ['screen and (max-width: 900px)', {
    seriesBarDistance: 15,
  }],
  ['screen and (max-width: 600px)', {
    seriesBarDistance: 10,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value[0];
      }
    }
  }],
  ['screen and (max-width: 550px)', {
    seriesBarDistance: 5,
    height:280,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value[0];
      }
    }
  }]
];
new Chartist.Bar('#bar', {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  series: [
    [52, 55, 46, 25, 98, 54, 24, 33, 48, 45, 24, 76],
    [52, 55, 46, 25, 98, 54, 24, 33, 48, 45, 24, 76] 
  ]
},{
    seriesBarDistance: 2,
    plugins: [
      Chartist.plugins.tooltip()
    ]
}, responsiveOptions);
```

Haven't tried it but I think this should work.

**Comment by jehad1990** [comment]
Oh ya :)

I missed this one, well it's working well.

thanks

**Comment by dominicrico** [comment]
You are welcome. @Globegitter  or @gionkunz  please close this.

**Comment by mohasinbagawan** [comment]
Hello,

I am working with angular 2 project and using chartist library to draw the graph. I am able to draw the graph as per my requirement. But when I add the tooltip plugin and try to access it. Graph is not drawn. I have done the npm install as well. Please help.

npm install chartist-plugin-tooltip --save

import * as Chartist from 'chartist';
import { ChartEvent, ChartType, ResponsiveOptions } from 'angular2-chartist';

private drawGraphMethod( graphArrayData: any, labelValues) {
            let  that = this;       
            let chart = new Chartist.Line('.ct-chart', {
            labels: labelValues,
            series: graphArrayData
             },
            {
            high: 100,
            low: 0,
            showArea: false,
            showLine: true,
            showPoint: true,
            fullWidth: true,
            axisX: {
                showGrid: false
            },
			// When I remove this, the graph is drawn
            plugins: [
                Chartist.plugins.tooltip()
            ]
        });
            chart.on('draw', function(data) {
            if ((data.type === 'grid' || data.type === 'label' || data.type === 'point')
                 && graphArrayData.length > 1) {
            data.element._node.addEventListener('click', () => { that.pointClickHandler(data); } );
            }
            });
      }

**Comment by mohasinbagawan** [comment]
raised a new issue - https://github.com/Globegitter/chartist-plugin-tooltip/issues/97
