### ISSUE TITLE
Plugin should require Chartist in UMD

### ISSUE THREAD

**Issue by SimonHarte** [Globegitter/chartist-plugin-tooltip#25]
If you load the chartist plugin in a module based environment it fails with the reference error "Chartist is not defined".

**Comment by SimonHarte** [comment]
https://github.com/gionkunz/chartist-plugin-accessibility/issues/1

**Comment by SimonHarte** [comment]
https://github.com/gionkunz/chartist-plugin-accessibility/issues/1

**Comment by Globegitter** [comment]
Would appreciate a PR :)
