### ISSUE TITLE
Bower: correct dependency for Chartist

### ISSUE THREAD

**Issue by SimonHarte** [Globegitter/chartist-plugin-tooltip#26]
A bower install currently fails with "bower - ECONFLICT - Unable to find suitable version for chartist".

In bower.json the dependency on chartist ist defined as version ~0.7.4 which restricts it to only patch versions of 0.7, this should be changed to ^0.7.4 to also include updates in its minor versions, since chartist is at 0.9.4 already.

**Comment by Globegitter** [comment]
Bumped to 0.9.4.
