### ISSUE TITLE
Issue with Chartist 0.7.4 Chartist.extend

### ISSUE THREAD

**Issue by gionkunz** [Globegitter/chartist-plugin-tooltip#3]
Hey there. I've found a bug in the Chartist.extend method that causes your plugin to fail. On the example you have created a pull request for there seems to be an issue with the label showing [object Object] as currencty and it's because the Chartist.extend function will extend null as an empty Object.

I'll fix that in the code but as longs as it's an open issue could you change this: https://github.com/Globegitter/chartist-plugin-tooltip/blob/master/src/scripts/chartist-plugin-tooltip.js#L10 to undefined instead of null?

Cheers
Gion

**Comment by Globegitter** [comment]
Yep just did - thanks for letting me know.
