### ISSUE TITLE
Install via bower miss the css files

### ISSUE THREAD

**Issue by boogiebug** [Globegitter/chartist-plugin-tooltip#36]
When I install the package via bower, I did not get the css files in dist folder. I guess that the list of css files are missing in the bower.json.

**Comment by eduardocasas** [comment]
+1

**Comment by dominicrico** [comment]
The thing is that @Globegitter has to release a new version. Bower installs always the latest release and in the v0.0.12 release are no css files included in the package.

**Comment by Globegitter** [comment]
@boogiebug @eduardocasas @dominicrico Anyone of you wants write access to the repo to be able to release new versions?

**Comment by lookfirst** [comment]
Let's do another release please!

**Comment by vool** [comment]
hi @Globegitter,

Just came here to say highlight the same issues with the bower package. 
I am happy to do the release if you want to grant me write access to the repo.

Keith

**Comment by vool** [comment]
Until a new version is released you can grab an up-to-date package via

bower install git@github.com:Globegitter/chartist-plugin-tooltip.git#master

**Comment by dominicrico** [comment]
@Globegitter If you would grand me write access then I would do a new release.

**Comment by daN4cat** [comment]
Yep, this should be fixed.

**Comment by daN4cat** [comment]
And `bower install git@github.com:Globegitter/chartist-plugin-tooltip.git#master` does not work either. Any tip?

**Comment by Globegitter** [comment]
@dominicrico you have access now :)

**Comment by daN4cat** [comment]
A fix would be great indeed.

**Comment by ealves-pt** [comment]
More or less a duplicate of #12.

Probably solved in the current release. Re-open the issue if the problem persists.
