### ISSUE TITLE
Dist files are not updated

### ISSUE THREAD

**Issue by DonSanto** [Globegitter/chartist-plugin-tooltip#38]
The files I get from bower install does not reflect the files in the dist folder. At least two options are missing; class and appendToBody.

*From bower*
![image](https://cloud.githubusercontent.com/assets/1021604/11236519/9d319c4a-8dda-11e5-9d59-414e8e507afa.png)

*From dist*
![image](https://cloud.githubusercontent.com/assets/1021604/11236538/b2b63f8a-8dda-11e5-9b15-0504cd941bb3.png)

**Comment by dominicrico** [comment]
see #36

**Comment by DonSanto** [comment]
Ah, thanks. I looked through that list two times and still i managed to miss it :/

**Comment by AlexanderKozhevin** [comment]
+1. I installed plugin from bower too. Not all files are present.
 "chartist-plugin-tooltip": "~0.0.12"
![screen shot 2015-12-22 at 15 12 13](https://cloud.githubusercontent.com/assets/4464561/11954972/6c0c5138-a8be-11e5-85d3-99f6a509f0ac.png)

**Comment by vool** [comment]
Until a new version is released you can grab via

bower install git@github.com:Globegitter/chartist-plugin-tooltip.git#master

**Comment by AlexanderKozhevin** [comment]
And there is one more issue. 
Can you add css file to **main** in bower file?
```
"main": [
    "./dist/chartist-plugin-tooltip.min.js"
  ],
```

**Comment by jasonsperske** [comment]
I just got caught by this bug :/ @vool's comment fixed it for me

**Comment by ealves-pt** [comment]
Perhaps this is fixed with the latest release.

Re-open this issue if the problem persists.
