### ISSUE TITLE
Branch: Master vs Dev

### ISSUE THREAD

**Issue by gitarno** [Globegitter/chartist-plugin-tooltip#41]
Good evening.

I'm using the library of you in version 0.0.12 via bower, however, to verify a need to use the library in Mobile, I noticed that the behavior of touchstart, touchend (which would be equivalent to mouse events) did not exist.

I did this fix on my fork. Created a branch specifies: hotfix / 0.0.13 in order to tow the project.

Analyzing the code available in the master branch, I noticed that there are 23 commits forward. My doubt was more by knowledge, because you have chosen to evolve corrections directly on the Master.

**Comment by Globegitter** [comment]
@gitarno This project is now in maintenance mode, meaning if people submit PRs, they look good I am happy to accept them. I am also happy to give others write access/ownership of the repo if they want to push to it more frequently/make releases.

So if you want happy to give you access to merge in your improvements and you can make a new dev branch etc :)

**Comment by gitarno** [comment]
Oh, right! I created a project fork, I can do the separation with certainty, after something, i sending.

**Comment by ealves-pt** [comment]
I don't think that for now we need to introduce git flow. But if we start to have a more active contribution perhaps we should write down some contribution guidelines and start doing some git flow.
