### ISSUE TITLE
Is it possible to use markup in tooltips?

### ISSUE THREAD

**Issue by atduskgreg** [Globegitter/chartist-plugin-tooltip#45]
Right now attempting to pass markup into the meta attribute leaves it coming through as the full markup string:

![screen shot 2015-12-31 at 4 05 53 pm](https://cloud.githubusercontent.com/assets/165/12069199/6dbd15d2-afd8-11e5-80b0-87dbd67a73cc.png)

Is there an option for getting this plugin to treat the string I'm passing in as html and actually render it as nodes in the DOM? Or could there be one?

**Comment by atduskgreg** [comment]
I went ahead and added an option to do this. There's a pull request.

**Comment by jondavidjohn** [comment]
I believe the correct way to do this with the current implementation is the build and return the markup in the `tooltipFnc` callback, that receives the meta / value as arguments

**Comment by ealves-pt** [comment]
This PR #60 adds that possibility.

**Comment by ealves-pt** [comment]
Solved with #60.
