### ISSUE TITLE
JSPM: Chartist is not defined

### ISSUE THREAD

**Issue by zenvisuals** [Globegitter/chartist-plugin-tooltip#50]
Hey Globegitter,

Great work over here. However I can't seem to use your plugin.

I am currently using Aurelia.IO and using JSPM as the package manager. It uses SystemJS to include the modules.

I have Chartist installed and I tried to install the chartist-plugin-tooltip. When I load the plugin, it says Chartist is not defined in shim.min.js.

I added the shim package override and it does not seem to work as well
```
"github:Globegitter/chartist-plugin-tooltip@0.0.12": {
  "main": "dist/chartist-plugin-tooltip",
  "registry": "github",
  "shim": {
    "dist/chartist-plugin-tooltip": {
      "deps": ["chartist"]
    }
  }
}
```
Any idea if I'm doing anything wrong over here?

Would really want to use your plugin for my project.

Thanks!
ZenVisuals

**Comment by Globegitter** [comment]
@zenvisuals Unfortunately have no experience with JSPM whatsoever. Would love to help!

**Comment by zenvisuals** [comment]
@Globegitter Just realised I pulled the wrong or outdated repo from JSPM, the version I pulled from didn't had reference to Chartist during AMD loading as you can see from here:
```
if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define([], function () {
      return (root.returnExportsGlobal = factory());
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like enviroments that support module.exports,
    // like Node.
    module.exports = factory();
  } else {
    root['Chartist.plugins.tooltips'] = factory();
  }
```
I referred to this issue: https://github.com/gionkunz/chartist-plugin-accessibility/issues/1
and figured out the solution but realised that the newer version of this repo had the change already.

Thanks for your message anyway :+1:
