### ISSUE TITLE
Create repo in npm

### ISSUE THREAD

**Issue by vladmiller** [Globegitter/chartist-plugin-tooltip#7]
Hello, would be nice if this plugin accessible from npm

**Comment by alex-pex** [comment]
+1

also : update packages.json and set the real release version (currently on v0.0.11 it says "version": "0.0.7")

**Comment by couellet** [comment]
+1

**Comment by Globegitter** [comment]
If anyone here wants access to the repo to push the package to npm would be happy to do so. Could also do it now but might not really get around to keeping it up-to-date etc.

**Comment by ealves-pt** [comment]
:+1: an NPM package would be super nice

**Comment by stuartsan** [comment]
👍 it would be really helpful if this were available via NPM

**Comment by Globegitter** [comment]
Again, I unfortunately don't have the time right now to maintain but happy to give any volunteer the rights so they can push it to npm

**Comment by ealves-pt** [comment]
@Globegitter I can help you publish it to NPM if you want.

**Comment by marcintokarski** [comment]
+1

**Comment by davorbadrov** [comment]
+1

**Comment by wwalser** [comment]
[https://github.com/CodeYellowBV/chartist-plugin-tooltip](This) resides [here](https://www.npmjs.com/package/chartist-plugin-tooltip) on NPM. Unfortunately it's slightly out of date and versions are hard to keep in sync since this repo doesn't change it's version number when code changes.

**Comment by Globegitter** [comment]
Just published the latest version on npm: https://www.npmjs.com/package/chartist-plugin-tooltips (as-is so not sure if it has all the right files, etc), but am happy to give anyone access rights to this repo and publish rights for npm.

@ealves-pt gave you access rights to both.
