### ISSUE TITLE
Contribution to chartist-plugin-tooltip

### ISSUE THREAD

**Issue by gionkunz** [Globegitter/chartist-plugin-tooltip#8]
Hi Markus

How open are you in terms of contribution on your plugin? 

I'd like to extend the functionality a bit but also make a few other changes. Things I had in mind:

- Remove dependency to jQuery
- Add more universal logic (eg. remove currency field but add an interpolation function or a pre / post field)
- Don't necessary rely on `display: none` to hide / show the label but give option to use classes to toggle visibility (can be used to animate) or option to animate directly (fadeOut with opacity)
- Provide Sass files and a CSS file in the dist version that contains a default tooltip style and default transition classes for hiding / showing

What do you think? If you let me do this, I'd pretty much rip your code apart :-D I know... There will be quite a lot changes. Do you have something in mind? I saw some settings there commented out...?

Cheers
Gion

**Comment by tuhoojabotti** [comment]
:+1: For these changes.

**Comment by Globegitter** [comment]
Ah sorry man just saw that - yes happy for you to do any changes/improvements you like. Had quite a few more ideas but my work moved me elsewhere for now.

**Comment by Globegitter** [comment]
Added you as collaborator @gionkunz :)

**Comment by optikfluffel** [comment]
:+1: (especially for wanting to get rid of jQuery)

**Comment by gionkunz** [comment]
Cool thanks @Globegitter I'll create a branch for my changes so you can review before we merge. Cheers Gion

**Comment by Globegitter** [comment]
:+1:

**Comment by ealves-pt** [comment]
Closed. Seems everything was solved with #32
