### ISSUE TITLE
Tag 0.0.17?

### ISSUE THREAD

**Issue by dandean** [Globegitter/chartist-plugin-tooltip#84]
Hello!

I was hoping there would be a tag for the latest npm release, but I don't see one in releases – the latest tag is v0.0.16, the latest npm release is 0.0.17.

Thanks!

**Comment by ealves-pt** [comment]
@dandean make sure you are looking at the proper NPM package: `https://www.npmjs.com/package/chartist-plugin-tooltips`

**Comment by dandean** [comment]
Oh sorry for the confusion. I mean git tags here:

https://github.com/Globegitter/chartist-plugin-tooltip/tags

We audit changes to our dependencies, and until this latest release we've been able to do that by comparing your release tags. We had to dig up commit SHA's instead with the npm release of 0.0.17.

Also, thank you for open sourcing this – it's been a really useful tool.

**Comment by ealves-pt** [comment]
@dandean done
