### ISSUE TITLE
Dist files are not updated

### ISSUE THREAD

**Issue by danielmahadi** [Globegitter/chartist-plugin-tooltip#9]
Hi Markus,

Thanks for this wonderful plugins.

I have a finding regarding the files in ```dist``` folder.
The latest changes for the tooltip class which is ```chartist-tooltip``` is not reflected.

Please tell me how can I help. :)

**Comment by Globegitter** [comment]
@danielmahadi quite busy right now so I added you as collaborator so you can update :)

**Comment by danielmahadi** [comment]
@Globegitter why not I make a pull request to this. :)

**Comment by danielmahadi** [comment]
@Globegitter I merged. the code. I will close this now. :)
