### ISSUE TITLE
Publish to NPM =]

### ISSUE THREAD

**Issue by roblav96** [Globegitter/chartist-plugin-tooltip#99]
#### `npm info chartist-plugin-tooltip`
```
version: '0.0.11',
modified: '2016-08-25T07:34:10.817Z',
```
v12 would be shweeeet =]

**Comment by bbenne10** [comment]
That's not the correct package. Check out `chartist-plugin-tooltips`. 0.0.17 is there.

**Comment by roblav96** [comment]
@bbenne10 Ah that would explain the jQuery dep lol thanks mate!

**Comment by bbenne10** [comment]
Glad I could help. You might want to also close this ticket, since there's no real issue.
